package com.spaceship.aws.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "spaceship")
public class SateliteEntity implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 5391948814562787183L;
	@DynamoDBHashKey  (attributeName = "name")
    @DynamoDBAutoGeneratedKey
    private String name;
    @DynamoDBAttribute
    private Double distance;
    @DynamoDBAttribute
    private String message;
    
    public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setDistance(Double distance) {
    	this.distance= distance ;
    }
    
	public Double getDistance() {
    	return distance;
    }
    
    public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}
   
}
